### ISSUE TITLE
Dark mode renders differently on chrome vs firefox

### ISSUE THREAD

**Issue by beyond9thousand** [sethcottle/littlelink#72] opened 2022-11-10 21:17 UTC
So I have noticed that for some reason, the deployed website looks darker on chrome based browsers while looking lighter on firefox, both of which look nowhere close to what is shown on the sample dark mode [website](https://littlelink.io/dark)

Am I missing something here?
![image](https://user-images.githubusercontent.com/77363063/201207635-4b741444-2551-41f8-8d42-d53b1038a958.png)
On the left I have chrome instances, followed by firefox to the right

**Comment by sethcottle** [comment] 2022-11-11 03:38
The sample site isn't updated often and isn't in sync with the latest commits, id you look at the source stylesheet, it's using the hardcoded OG dark mode values from before the repo received support for Light, Dark, and Auto modes. That's probably something I should actually take the time to pull in and update so that it accurately reflects the latest dark mode updates.

See #40. This was a large commit that should have been broken out a bit more, but the gist was removing the hardcoded value for dark theme and instead supporting `color-scheme: dark;`. This is CSS property that is supported by Chrome, Edge, Firefox, Opera, Safari, and their native mobile variations, as well as Samsung Internet, ..etc.

The differences you're seeing is due to the site rending with the each browsers unique user agent stylesheet. Google Chrome uses `#121212` as their dark mode baseline, which is derived from their Material Design Guidelines. Firefox, Safari, Edge, ..etc all use something slightly different as their default dark theme. This also interprets text color for body styles, headings, ..etc.

If you want it the same everywhere and not have your site default to the stylesheet supplied by each browser/system, I would recommend removing `color-scheme: dark;` and replacing it with `background-color: #VALUE;` you'll also need to define in the CSS `color` values for `body`, `h1`, ..etc.

**Comment by sethcottle** [comment] 2022-11-11 03:57
Marking this as closed since it's expected behavior given the implementation.

**Closed by sethcottle** 2022-11-11 03:57 UTC

**Comment by beyond9thousand** [comment] 2022-11-11 07:13
Thanks for the answer :)
